---
title: "rMarkdown Figures"
author: "Jonathan Huang"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true 
    toc_float: true
    theme: cosmo
---
<!-- fig.path to set output  -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  #display code?
                      message = FALSE, #display messages?
                      warning = FALSE, #display 
                      fig.path = "../output") #HELP edit file path to save in output folder
```
## Install Libraries
```{r, echo= TRUE}
#install library
library(kableExtra)
library(palmerpenguins)
library(tidyverse)
library(prettydoc)
library(gt)
library(gtExtras)
```

## View data 
```{r}
glimpse(penguins)
```


## Making Tables in Markdown

### Summary table
```{r print.table.pdf, echo=TRUE}
penguins %>% 
  drop_na() %>%   #drop NAs
  group_by(year, sex) %>% #group by to summarize
  summarise("Bill Length(mm)" = mean(bill_length_mm, na.rm = TRUE),
            "Mass(g)" = mean(body_mass_g, na.rm = TRUE)) %>%
  kbl() %>%  # make it a kable table
  kable_classic()%>% #change table style
  row_spec(c(2,4,6), bold = T, color = "black", background = "lightblue") %>%  #edit row and text color 
  kable_styling(full_width = FALSE) # make table only as long as needed

  
```


## Making a *PLOT*
```{r violinplot.pdf,}
penguins %>% 
  mutate(year = as_factor(year), #make factor 
         body_mass_g= as.numeric(body_mass_g)) %>%  # make numeric
  drop_na() %>%  # remove NAs
  mutate(year = fct_reorder(year, body_mass_g), #reorder other factor based on these two
         year = factor(year, levels = c("2007","2008","2009"))) %>% #order factor of year
  ggplot(aes(x = year, y = body_mass_g, fill = sex))+ #specify plot axis
  geom_violin()+ #make basic violin plot
  theme_bw()
  
```


